language: go
go:
 - "1.x"

os:
 - osx
 - windows

install: true

env:
  global:
    - CODECOV_TOKEN="6ac7ddfb-dfa8-4ac5-8d75-527a81eed7f3"

script: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
